# config.yaml
# Geometric and Quantity Parameters
area_size: [[0.0, 100.0], [0.0, 100.0]]     # km
instance_type_distribution: {R: 0.4, C: 0.2, RC: 0.4}
dist_fun: "2-norm"
set_edge: False

# Those Variables should be input via argerparser (to make generator more flexible)
num_customers: 100
num_charging_stations: 20
num_cluster: 5

# Vehicle
# vehicle_ac_limit_kw: null
vehicles_profiles:
  - name: "Rivian_EDV"                      # Amazon-Rivian Electric Truck (Last-Mile)
    type: "last-mile"
    speed: 40.0                             # km/h  (Within City)
    battery_capacity: 135                   # kWh (135)
    consumption_per_distance: 0.5           # kWh/km
    loading_capacity: 1.2                   # tons (Capacity)
    notes: "Custom Rivian EDV used by Amazon; ~150 miles (~241 km) range."

  - name: "Mercedes_eActros_600"            # Amazon (Middle-Mile)
    type: "middle-mile"
    speed: 65.0                             # km/h  (Highway)
    battery_capacity: 621                   # kWh
    consumption_per_distance: 1.24          # kWh/km
    loading_capacity: 22.0                  # tons (Capacity)
    notes: "Mercedes-Benz eActros 600 heavy-duty truck; ~500 km (~311 miles) range."

  - name: "Slate_Pickup"                    # Bezos Earth Fund (Light-Duty)
    type: "light-duty"
    speed: 50.0                             # km/h
    battery_capacity: 52.7                  # kWh
    consumption_per_distance: 0.22          # kWh/km
    loading_capacity: 0.65                  # tons (Capacity)
    notes: "Slate Auto low-cost EV pickup truck (under $20k after incentives)."

# Charging Station
charging_profiles:
  - name: "AC_L2_11kW"
    type: "AC_L2"
    power_kw: 11.5
    efficiency: 1.00         
  - name: "DC_Fast_150kW"
    type: "DC_Fast"
    power_kw: 150.0
    efficiency: 1.00      
  - name: "DC_Ultra_350kW"
    type: "DC_Ultra"
    power_kw: 350.0
    efficiency: 1.00      

# instance time (hh:mm)
instance_time_range: ["00:00", "23:59"]
working_schedule_profiles:
    - name: "Standard_Working_Hours"
      start: "8:00"
      end: "20:00"



####################################### Policy Configurations #######################################
# cluster_assignment.py
rc_customers_assign_policy: null
rc_customers_assign_policy_list: ["fixed"]
rc_customers_assign_policy_config:
    "fixed":
      fixed_rc_customer_ratio: [0.3, 0.7]  # [random_ratio, clustered_ratio]
      score: 100
    "random":
      score: 100

# time window configs
# Score is used for weighted random sampling (like a ratio controler)
# time_window.py
time_window_policy: null
time_window_policy_list: ["narrow", "wide"]
time_window_policy_config:
    "narrow":
      alpha: 0.05
      beta: 0.005
      score: 0
    "wide":
      alpha: 0.5
      beta: 0.2
      score: 100

# demand.py
demands_policy: null
demands_policy_list: ["20_80","random","uniform"]
demands_policy_config:
    "20_80":
      small_package_weight_ratio: 0.2 # small package := weight <= 20% * Capacity.
      small_weight_range: [0.001, 0.01]
      large_weight_range: [0.01, 0.1]
      score: 50
    "uniform":
      score: 0
    "random":
      score: 40
      weight_range: [0.001, 0.1]

# service_time.py
service_time_policy: null
service_time_policy_list: ["random", "cargoweight"]
service_time_policy_config:
    "random":
      integer: True
      round_digits: 2
      st_range: [1, 10]
      score: 100
    "cargoweight":
      base_service_time: 3
      weight_coefficient: 30
      score: 100

# cluster_number.py
cluster_number_policy: null
cluster_number_policy_list: ["fixed", "random"]
cluster_number_policy_config:
    "fixed":
      fixed_cluster_num: 5
      score: 100

    "random":
      min_cluster_num: 3
      max_cluster_num: 10
      score: 100

# cluster_assignment.py
cluster_assignment_policy: null
cluster_assignment_policy_list: ["balanced", "dirichlet"]
cluster_assignment_policy_config:
    "balanced":
      fixed_cluster_assignment: [0.2, 0.8]  # [random_ratio, clustered_ratio]
      score: 100
    "dirichlet":
      dirichlet_alpha: 1.0
      score: 0
#############################################################################################################

# Auxiliary Parameters for Clustered and RC Instances
min_radius_frac_of_R: 0.25
max_radius_frac_of_R: 0.9
max_trials_per_cs: 5000
dummy_size: 5

